alpine arm dockerfile
dani-garcia/bitwarden_rs pull request #1151
Opened 2020-09-21 22:41 UTC by dr-bonez

also adds catatonit for sigterm handling and strips the binary

2020-09-22 03:43 UTC, jjlin commented on docker/Dockerfile.j2
> +RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing catatonit
I don't think this should be added, as it special-cases the Alpine arm32v7 build for no obvious reason. If you really want this, you can use `docker run --init ...`.

2020-09-22 15:49 UTC, dr-bonez commented on docker/Dockerfile.j2
> +RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing catatonit
I talked to @dani-garcia about this in matrix, he said to try it for only this build target until signal handling is managed in the binary itself.

2020-09-25 19:32 UTC, dani-garcia requested changes
Sounds good to me, add the arm arch to this file so the images get built by docker too:
https://github.com/dani-garcia/bitwarden_rs/blob/master/hooks/arches.sh#L24

About the init thing, ultimately I want it handled by the binary and that's happening when async rocket gets released, but I don't know when that's happening. My initial idea was to just add it to this one as a test then potentially have something similar in the others, just a small init to handle the shutdown signal, but I can see how a short term solution like that might not be worth it when you can do the --init command like @jjlin says. Maybe it could be handled by the start script (https://github.com/dani-garcia/bitwarden_rs/blob/master/docker/start.sh)?

2020-09-25 19:32 UTC, dani-garcia commented on docker/Dockerfile.j2
> +{%     set runtime_stage_base_image = "cmosh/alpine-arm" %}
```suggestion
{%     set runtime_stage_base_image = "cmosh/alpine-arm:3.6" %}
```

Let's add the version number like the others to try to make the images as reproducible as possible

2020-09-26 20:06 UTC, dr-bonez commented
We could use `tini` instead of `catatonit` since evidently it is what docker recommends, but imo the callee shouldn't need to have knowledge as to whether the container has a proper init system in order to call it correctly, so I'm not a fan of the `--init` solution.

2020-10-03 18:47 UTC, dani-garcia commented
At the end of the day, I'm surprised we haven't gotten more complaints about the way we handle sigterm, and I believe we should add something similar to the rest of the images, I think testing it in this new image is a good way to see how well it could work on the rest, and we can change them once we see this one working out (or we can leave them as is until rocket 0.5 is released and handles this)

2020-10-03 18:47 UTC, merged