Save last login timestamp for users and show it on admin page
dani-garcia/bitwarden_rs pull request #1245
Opened 2020-11-30 00:50 UTC by janost

Feature request from #246.

This change implements saving last login date and time for users to the database and adds this information to the admin panel's user list. I also added the user creation date to the admin page.

2020-11-30 05:48 UTC, jjlin commented
I don't think it's necessary to add a new `last_login` column. The device `updated_at` timestamp is already updated on each login, so you could just get that instead, e.g.
```sql
SELECT d.updated_at
FROM devices d INNER JOIN users u ON d.user_uuid = u.uuid
WHERE u.email = 'user@example.com'
ORDER BY d.updated_at DESC LIMIT 1
```

2020-11-30 07:25 UTC, BlackDex commented
I was thinking about this my self a few weeks back. And i think there is an other way without notifying the database.

I think you can use the `device` table for this. It has an updated at field. With that you can show when last login and with which device.

2020-11-30 13:21 UTC, janost commented
Thanks for the review @jjlin, @BlackDex!

If I understand the API correctly, what you're proposing is not functionally equivalent to this implementation.
The current `last_login` field only gets updated if a user logs in with username and password.
The `updated_at` field in the device model gets updated with a new timestamp even if the application is just locked, for example the user uses biometrics to unlock the Android app, since it requests a refresh token.

I'm fine with either implementation, we just need to agree on the term "Last login".

2020-11-30 17:42 UTC, jjlin commented
As an admin, I think I would want to know when a user was "last active" or "last online". The `updated_at` field is updated whenever the user logs in fresh, or if they're already logged in, whenever the cached token is expiring "soon" (in the next hour, AFAIK) and needs refreshing. The token refresh can happen even if the user simply opens the app, but doesn't actually unlock it. I think `updated_at` is a reasonable first approximation for last activity; ideally, a user's last sync, last cipher written, etc. could be factored in as well, but these aren't tracked currently.

IMO at least, last login (the current implementation) is not very useful since users can log in once via the browser extension or mobile app and then stay logged in indefinitely. So you could have a very active user whose "last login" is months or even years ago.

2020-11-30 17:50 UTC, BlackDex commented
I my self was thinking about a more detailed overview when for example clicking on a user, and show all active devices. Also with the ability to deauthorize per device. But for the main user overview i agree with @jjlin .

2020-11-30 21:02 UTC, janost commented
@jjlin @BlackDex You're right, I'm convinced. :+1: 
I've changed the implementation, please check it out.

2020-12-01 05:55 UTC, jjlin commented on src/static/templates/admin/users.hbs
> +                                <span class="d-block">Last login: {{last_login}}</span>
I think this would be more accurately labeled `Last active` or similar.

2020-12-01 05:58 UTC, jjlin commented on src/db/models/device.rs
> +    pub fn find_latest_active_by_user(user_uuid: &str, conn: &DbConn) -> Option<Self> {
I'd suggest instead having a `last_active` method for `User`, which might later be extended to consider more than just device token updates.

2020-12-01 21:35 UTC, janost commented
@jjlin @BlackDex I changed the implementation according to your feedback.

2020-12-01 22:47 UTC, jjlin commented on src/db/models/user.rs
> +        let last_device = Device::find_latest_active_by_user(self.uuid.as_str(), conn);
`&self.uuid` would be more efficient. Looks good otherwise.

2020-12-01 23:50 UTC, janost commented on src/db/models/user.rs
> +        let last_device = Device::find_latest_active_by_user(self.uuid.as_str(), conn);
Thanks, I missed that. Fixed.

2020-12-02 20:53 UTC, BlackDex commented
Looking at it visually it's take up a lot of space. Also very much on a mobile (small screen) device.
I'm thinking about how to show this a bit nicer.

2020-12-02 21:13 UTC, BlackDex commented
I have something like this as the first row of the user:
```html
                    <tr>
                        <td colspan="5">
                            <span>Created at: {{created_at}}</span> | <span>Last active: {{last_active}}</span>
                        </td>
                    </tr>
```
With the following at every `<td>` in the next `<tr>`:
```html
 class="border-top-0"
```

Which then looks like this:
![image](https://user-images.githubusercontent.com/610450/100931996-877ce400-34eb-11eb-967a-e845a0863dbe.png)

I'm also not quite sure about this approach.

2020-12-02 21:27 UTC, jjlin commented
It might be useful to sort on these values sometimes, so maybe they could each go under a separate column, formatted like
```
2020-01-01
12:34:56
```
I can't imagine how mobile devices would ever display this much data nicely, so that may be a lost cause anyway.

2020-12-02 21:32 UTC, BlackDex commented
@jjlin The table is responsive, so it kinda looks ok, you have to scroll left/right to see all.
I do have a lot of orgs with this test user, but it's of course possible.

Maybe we need to create some kind of overlay when there are more then x orgs a user is a member of.
That would create some space. And sorting on date-time is maybe already active. I have to check that JS-Library.

2020-12-02 21:59 UTC, BlackDex commented
What about using popover for the orgs when there are more then x?
https://thednp.github.io/bootstrap.native/#popoverExamples

2020-12-02 22:05 UTC, BlackDex commented
or, maybe just a collapse. That would be better for the searchbox i think.

2020-12-02 22:28 UTC, BlackDex commented
I think that Datatables can sort dates by default especially when using the ISO Format.

2020-12-03 07:50 UTC, BlackDex commented
This example i found looks ok for the orgs: https://jsfiddle.net/g4q5vp2f/1/ 
WIth that in place, we can just shrink that column, and add two new ones for last active and created

2020-12-03 10:32 UTC, janost commented
@BlackDex What is your opinion on merging this and working on the UI changes in a separate issue?
I feel like it is out of scope of this feature implementation and it might need further discussion.

2020-12-03 13:13 UTC, BlackDex requested changes
I think that is a good idea.
I'm also comfortable to merge this, since it's not something which could break other items.

I have only one remark left see my suggestion.

2020-12-03 13:13 UTC, BlackDex commented on src/db/models/user.rs
> +        match last_device {
I would shorten this and remove the `let last_device`, something like this.
```rust
match Device::find_latest_active_by_user(&self.uuid, conn) {
```

2020-12-03 15:26 UTC, BlackDex commented
Also, would be nice if you can merge these commit's all into one :).

2020-12-03 16:09 UTC, janost commented
@BlackDex Done! :+1:

2020-12-03 16:26 UTC, BlackDex approved these changes

2020-12-08 14:31 UTC, merged

2020-12-08 14:31 UTC, dani-garcia commented
Nice, thanks!

2021-01-07 14:54 UTC, omueller commented
Many thanks for this new very useful feature !     A way to sort the date by "last active" would also be great, and/or a way to export all data as CSV (then we can sort over the terminal or in a spreadsheet program).

2021-01-07 15:19 UTC, BlackDex commented
I'm planning to do a bit of a restyle of that specific interface, that should make sorting by date possible.
Don't know when it will be done.

2021-01-07 15:47 UTC, omueller commented
Great, thanks for the update @BlackDex!